# trizen
# Autogenerated from man page /usr/share/man/man1/trizen.1.gz
complete -c trizen -s q -l quiet -d 'Display minimal output'
complete -c trizen -s a -l aur -d 'Perform only AUR operations'
complete -c trizen -s r -l regular -d 'Perform only regular pacman operations (the opposite of --aur)'
complete -c trizen -l stats -d 'Display statistics for the installed packages'
complete -c trizen -l nocolors -d 'Disable ANSI colors'
complete -c trizen -l forcecolors -d 'Enable colors even when not writing to STDOUT'
complete -c trizen -l debug -d 'Enable verbose mode'
complete -c trizen -s s -l search
complete -c trizen -s i -l info
complete -c trizen -s m -l maintainer
complete -c trizen -s p -l pkgbuild
complete -c trizen -s l -l local
complete -c trizen -s u -l sysupgrade
complete -c trizen -s y -l refresh
complete -c trizen -s c -l clean
complete -c trizen -l devel
complete -c trizen -l show-ood
complete -c trizen -l noinfo
complete -c trizen -l nopull
complete -c trizen -l noedit
complete -c trizen -l nobuild
complete -c trizen -l noinstall
complete -c trizen -l noconfirm
complete -c trizen -l needed
complete -c trizen -l asdeps
complete -c trizen -l asexplicit
complete -c trizen -l skipinteg
complete -c trizen -l movepkg
complete -c trizen -l movepkg-dir
complete -c trizen -l clone-dir
complete -c trizen -l editor
complete -c trizen -l pager-mode
complete -c trizen -l pager
complete -c trizen -l ignore
complete -c trizen -o Qua
complete -c trizen -o Qma
complete -c trizen -s d -l with-deps

